### ISSUE TITLE
Hardware requiremements for 5B model

### ISSUE THREAD

**Issue by LeeKeyu** [stdstu12/YUME#15]
Hi authors, thanks a lot for your contributions.
My question is about the GPU usage of the newly updated YUME 1.5 5B version. I tried to run the inference script with 2*40g GPUs and got OOM. Could you please specify about the hardware requirements for testing and training the 5B model?
Thanks very much!

**Comment by LeeKeyu** [comment]
Thank you for your reply! Also I found a bug that when using >= 2 gpus for inference, some images in the jpg/ folder will be skipped and some will be evaluated more than once. Maybe the sampling code needs some modification.

**Comment by stdstu12** [comment]
We used 40 A100 GPUs. Thank you for pointing out the issue; it has been fixed.

**Comment by wine-plum** [comment]
> We used 40 A100 GPUs. Thank you for pointing out the issue; it has been fixed.

Hi, could you please share the approximate time required for each stage during the training process?
